--DROP IF EXISTS USERS;
--
--DROP IF EXISTS MESSAGES;

CREATE TABLE  IF NOT EXISTS USERS
(
   USERNAME varchar(12) PRIMARY KEY NOT NULL,
   PASSWORD varchar(12) NOT NULL,
   FIRST_NAME varchar(30) NOT NULL,
   LAST_NAME varchar(30) NOT NULL
);
CREATE TABLE IF NOT EXISTS MESSAGES
(
   MESSAGE_ID int PRIMARY KEY AUTO_INCREMENT NOT NULL,
   MESSAGE_TIME timestamp NOT NULL,
   MESSAGE_TEXT varchar(255) NOT NULL,
   SENDER varchar(12) NOT NULL,
   RECEIVER varchar(12) NOT NULL,
   FOREIGN KEY (SENDER) REFERENCES USERS(USERNAME),
   FOREIGN KEY (RECEIVER) REFERENCES USERS(USERNAME)
);
--ALTER TABLE MESSAGES AUTO_INCREMENT=1001;